language: php
php:
    - '7.0'
    - '7.1'
    - hhvm
    - hhvm-nightly
    - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly
        - php: hhvm-nightly

before_script:
    - composer install

script:
    - ./vendor/bin/phpunit --coverage-text
    - bash ./docker/travis-ci.sh
