wolnosciowiec.api.deployer.deploy:
    path: /{apiKey}/deploy/{repositoryName}
    defaults:
        _controller: "AppBundle:Deploy:index"
    requirements:
        apiKey: "%api_key%"

wolnosciowiec.api.deployer.index:
    path: /
    defaults:
        _controller: "AppBundle:Default:index"
