services:
    wolnosciowiec.api.deployer.handler:
        class: AppBundle\Service\Deployer\DeployHandler
        arguments:
            branchMatcher: "@wolnosciowiec.api.deployer.branch_matcher"

    wolnosciowiec.api.deployer.handler.heroku:
        class: AppBundle\Service\Deployer\Method\HerokuMethod
        arguments:
            fetcher: "@wolnosciowiec.api.deployer.fetcher"
            client: "@wolnosciowiec.api.deployer.client"
        tags:
            - { name: deployer }

    wolnosciowiec.api.deployer.handler.thin_deployer:
        class: AppBundle\Service\Deployer\Method\ThinDeployerMethod
        arguments:
            client: "@libraries.guzzlehttp.client"
        tags:
            - { name: deployer }

    wolnosciowiec.api.deployer.fetcher:
        class: AppBundle\Service\Fetcher\GitFetcher
        arguments:
            wrapper: "@libraries.git"
            repositoriesStoragePath: "%storage_path%"
            repositoriesOverridePath: "%storage_override_path%"

    wolnosciowiec.api.deployer.client:
        class: AppBundle\Service\TargetPreparation\HerokuClient

    wolnosciowiec.api.deployer.branch_matcher:
        class: AppBundle\Service\BranchMatcher

    wolnosciowiec.api.deployer.exception_controller:
        class: AppBundle\Controller\ExceptionController
        arguments:
            - "@twig"
            - "%kernel.debug%"

    libraries.git:
        class: GitWrapper\GitWrapper
        shared: false

    libraries.guzzlehttp.client:
        class: GuzzleHttp\Client
        shared: false


