version: '2'

networks:
    deployer:

services:
    deployer_app:
        build:
            context: ./container
            dockerfile: Dockerfile
        expose: 
            - 80
        ports:
            - 7011:80
        volumes:
            - ../:/var/www
        networks:
            deployer:
                aliases:
                    - deployer_app
        env_file:
            - ./.env

